### ISSUE TITLE
google::protobuf::FatalException when running tests on macOS

### ISSUE THREAD

**Issue by sbrunk** [SciScala/NDScala#1]
Trying to run the tests on macOS (catalina) results in the following error on my machine, starting with the `add` test:

```
$ bloop test onnxscala
ONNXScalaTensorSpec:
Tensor
- should zero
Tensor
- should one
Tensor
- should fill
Tensor
[E] Failed to initialize communication: null
[E] [libprotobuf ERROR google/protobuf/descriptor_database.cc:334] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[E] [libprotobuf FATAL google/protobuf/descriptor.cc:1370] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
[E] libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
```

I guess it's coming from the JavaCPP Preset for ONNX which uses protobuf but I haven't been able to pinpoint the exact cause. Any idea what it might be? It's working fine on a Linux machine.

**Comment by sbrunk** [comment]
So it seems this is a common issue with in combination with certain protobuf versions and can also occur when using onnx from Python: https://github.com/onnx/onnx/issues/2808

One interesting observation is that when I run `tensorflow/test` followed by `onnxscala/test` from sbt, it works! So TF Scala might pull in a working protobuf version.

**Comment by EmergentOrder** [comment]
This should be fixed, as I've replaced the ONNX JavaCPP Preset w/ ScalaPB in ONNX-Scala

**Comment by sbrunk** [comment]
Yes I can confirm that it's working now on my machine. Thanks @EmergentOrder!
